# Generated by Django 4.2.6 on 2023-11-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='state',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ожидаем подтверждения'), (2, 'Подтверждён'), (3, 'Ждём категорию'), (4, 'Ждём название')], default=1, verbose_name='Состояние'),
        ),
    ]
