# Generated by Django 4.2.6 on 2023-11-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='auth_code',
            field=models.IntegerField(null=True),
        ),
    ]
