# Generated by Django 4.2.6 on 2023-11-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_alter_goalcategory_board'),
        ('bot', '0005_remove_tguser_auth_code_tguser_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='create_goal_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='goals.goalcategory', verbose_name='Категория для создания цели'),
        ),
    ]
